### 1D code CMI simulation

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import product

Defining the code size and partitions into subregions 

In [2]:
#Total number of qubits 
N = 10 
#Size of middle region 
R = 2

#Subregion sizes
A = 2
B = 2*R 
C = N - A - B 

We calcualte CMI as:

\begin{equation}

CMI = I(A:C|B) = H(AB) + H(BC) - H(ABC) - H(B),

\end{equation}

where $H(Q)$ is the Shannon entropy of the $Q$ subregion:

\begin{equation}

H(Q) = \sum_{s} Pr(s) \cdot log_2 Pr(s), 

\end{equation}


\begin{equation}

Pr(s) = p^{|s|}(p-1)^{N-|s|},

\end{equation}

where $p$ is the noise rate (probability of a physical qubit to flip), $s \in \{0,1\}^N$ is the vector of syndormes (list of flip - entry 1, or no flip - entry 0) for each physical qubit, and N is the total number of qubits. For subregion Q, we only consider the substring (part of the vector) corresponding to qubits in Q.



Generating all possible strings of 0's and 1's of length N. We need to sum over them to calculate CMI.

In [ ]:
strings = list(product([0, 1], repeat=N))

strings = np.array(strings)

print(strings)
print(strings.dim)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
10240
